[package]
name = "yas-wire"
version = "0.2.3"
edition.workspace = true
description = "YAS protocol wire codecs and schema primitives"
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
lz4_flex = { version = "0.14", default-features = false, features = ["alloc", "safe-encode", "safe-decode"] }

[build-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1"
