[package]
name = "yas-guest"
version = "0.2.6"
edition.workspace = true
description = "Guest SDK for YAS Wasmi extensions"
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = []

[dependencies]
yas-wire = { workspace = true }
getrandom = { version = "0.4", default-features = false }
hashbrown = { version = "0.17", default-features = false }
siphasher = { version = "1", default-features = false }
blake3 = { version = "1", default-features = false }

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
