//! Server-owned native YAS Font catalogue.

use std::sync::Arc;
use std::time::Duration;

use notify::Watcher;
use yas_fonts::{FontCatalog, FontExportPolicy};

pub(crate) const MAX_CONCURRENT_FETCHES: usize = 4;
pub(crate) const MAX_SCAN_DURATION: Duration = Duration::from_secs(30);
const RESCAN_DEBOUNCE: Duration = Duration::from_millis(250);

#[derive(Clone)]
pub(crate) struct Catalog {
    current: Arc<std::sync::RwLock<CatalogSnapshot>>,
    revisions: tokio::sync::watch::Receiver<u64>,
}

#[derive(Clone)]
pub(crate) struct CatalogSnapshot {
    pub(crate) revision: u64,
    pub(crate) catalog: Arc<FontCatalog>,
}

impl Catalog {
    pub(crate) fn current(&self) -> CatalogSnapshot {
        self.current
            .read()
            .expect("font catalogue lock poisoned")
            .clone()
    }

    pub(crate) fn subscribe(&self) -> tokio::sync::watch::Receiver<u64> {
        self.revisions.clone()
    }

    /// A catalogue that never changes (tests; a net-only server's empty one).
    pub(crate) fn fixed(catalog: Arc<FontCatalog>) -> Self {
        let (tx, revisions) = tokio::sync::watch::channel(1);
        let _ = tx;
        Self {
            current: Arc::new(std::sync::RwLock::new(CatalogSnapshot {
                revision: 1,
                catalog,
            })),
            revisions,
        }
    }
}

#[derive(Clone)]
pub(crate) struct Service {
    catalog: Catalog,
    fetch_slots: Arc<tokio::sync::Semaphore>,
    advertised: bool,
}

impl Service {
    pub(crate) async fn from_env() -> Self {
        let advertised = !std::env::var("YAS_FONTS").is_ok_and(|value| value == "0");
        // Export usable fonts by default. The authenticated server applies
        // the explicit opt-out and each face's embedding restrictions.
        let export_policy =
            configured_export_policy(std::env::var("YAS_FONT_EXPORT").ok().as_deref());
        // Install the watcher before the initial scan so a real mutation
        // during a long scan requests a follow-up snapshot. Access events
        // generated by the scan itself are filtered by queue_font_event.
        let (event_tx, mut events) = tokio::sync::mpsc::channel(1);
        let watcher = advertised.then(|| font_watcher(event_tx.clone())).flatten();
        let mut unfinished_scan: Option<tokio::task::JoinHandle<FontCatalog>> = None;
        let catalog = if advertised {
            let mut scan = tokio::task::spawn_blocking(move || FontCatalog::scan(export_policy));
            match tokio::time::timeout(MAX_SCAN_DURATION, &mut scan).await {
                Ok(Ok(catalog)) => catalog,
                Ok(Err(error)) => {
                    eprintln!("yas-server: font catalogue task failed: {error}");
                    empty_catalog(export_policy)
                }
                Err(_) => {
                    // A running spawn_blocking task cannot be aborted. Keep its
                    // handle so the update worker can await and publish it,
                    // without starting an overlapping rescan.
                    unfinished_scan = Some(scan);
                    eprintln!(
                        "yas-server: font catalogue scan exceeded {}s; publishing an empty catalogue",
                        MAX_SCAN_DURATION.as_secs()
                    );
                    empty_catalog(export_policy)
                }
            }
        } else {
            empty_catalog(export_policy)
        };
        let catalog = Arc::new(catalog);
        let (revision_tx, revisions) = tokio::sync::watch::channel(1);
        let current = Arc::new(std::sync::RwLock::new(CatalogSnapshot {
            revision: 1,
            catalog: Arc::clone(&catalog),
        }));
        if advertised {
            let current = Arc::clone(&current);
            tokio::spawn(async move {
                if let Some(scan) = unfinished_scan {
                    match scan.await {
                        Ok(next) => publish_catalog(&current, &revision_tx, next),
                        Err(error) => {
                            eprintln!("yas-server: font catalogue task failed: {error}");
                        }
                    }
                }

                let Some(mut _watcher) = watcher else {
                    return;
                };
                loop {
                    if events.recv().await.is_none() {
                        return;
                    }
                    tokio::time::sleep(RESCAN_DEBOUNCE).await;
                    while events.try_recv().is_ok() {}
                    let mut scan =
                        tokio::task::spawn_blocking(move || FontCatalog::scan(export_policy));
                    let next = match tokio::time::timeout(MAX_SCAN_DURATION, &mut scan).await {
                        Ok(Ok(next)) => next,
                        Ok(Err(error)) => {
                            eprintln!("yas-server: font catalogue task failed: {error}");
                            continue;
                        }
                        Err(_) => {
                            // Dropping this handle would detach a scan which
                            // spawn_blocking cannot cancel. Await it so at most
                            // one catalogue scan exists at a time.
                            eprintln!(
                                "yas-server: font catalogue rescan exceeded {}s; waiting for completion",
                                MAX_SCAN_DURATION.as_secs()
                            );
                            match scan.await {
                                Ok(next) => next,
                                Err(error) => {
                                    eprintln!("yas-server: font catalogue task failed: {error}");
                                    continue;
                                }
                            }
                        }
                    };
                    // Recreate the registrations after every event so a font
                    // directory which did not exist at startup replaces its
                    // nearest-parent watch with a recursive watch of itself.
                    if let Some(next_watcher) = font_watcher(event_tx.clone()) {
                        _watcher = next_watcher;
                    }
                    publish_catalog(&current, &revision_tx, next);
                }
            });
        }
        Self {
            catalog: Catalog { current, revisions },
            fetch_slots: Arc::new(tokio::sync::Semaphore::new(MAX_CONCURRENT_FETCHES)),
            advertised,
        }
    }

    pub(crate) fn catalog(&self) -> Option<Catalog> {
        self.advertised.then(|| self.catalog.clone())
    }

    pub(crate) fn fetch_slots(&self) -> Arc<tokio::sync::Semaphore> {
        Arc::clone(&self.fetch_slots)
    }

    #[cfg(test)]
    pub(crate) fn disabled_for_test() -> Self {
        Self::disabled()
    }

    /// No catalogue, nothing scanned or watched (a net-only server).
    pub(crate) fn disabled() -> Self {
        Self {
            catalog: Catalog::fixed(Arc::new(empty_catalog(FontExportPolicy::Deny))),
            fetch_slots: Arc::new(tokio::sync::Semaphore::new(MAX_CONCURRENT_FETCHES)),
            advertised: false,
        }
    }
}

fn publish_catalog(
    current: &std::sync::RwLock<CatalogSnapshot>,
    revisions: &tokio::sync::watch::Sender<u64>,
    next: FontCatalog,
) {
    let next = Arc::new(next);
    let mut guard = current.write().expect("font catalogue lock poisoned");
    if guard.catalog.families() == next.families() {
        return;
    }
    guard.revision = guard.revision.saturating_add(1);
    guard.catalog = next;
    let revision = guard.revision;
    drop(guard);
    revisions.send_replace(revision);
}

fn font_watcher(events: tokio::sync::mpsc::Sender<()>) -> Option<notify::RecommendedWatcher> {
    let roots: Vec<std::path::PathBuf> = yas_fonts::font_dirs()
        .into_iter()
        .map(std::path::PathBuf::from)
        .collect();
    #[cfg(unix)]
    let roots = {
        let mut roots = roots;
        roots.push("/etc/fonts".into());
        if let Some(home) = std::env::var_os("HOME") {
            roots.push(std::path::PathBuf::from(home).join(".config/fontconfig"));
        }
        roots
    };
    let relevant_roots = roots.clone();
    let mut watcher = notify::recommended_watcher(move |event: notify::Result<notify::Event>| {
        queue_font_event(&events, &relevant_roots, event);
    })
    .map_err(|error| eprintln!("yas-server: cannot watch font directories: {error}"))
    .ok()?;

    let mut watched = std::collections::BTreeMap::new();
    for root in roots {
        let exact = root.is_dir();
        let mut path = root.as_path();
        while !path.exists() {
            let Some(parent) = path.parent() else {
                break;
            };
            path = parent;
        }
        // Missing system roots such as /Library/Fonts on Linux must not turn
        // into a watch of the whole filesystem.
        if path.parent().is_none() {
            continue;
        }
        watched
            .entry(path.to_path_buf())
            .and_modify(|recursive| *recursive |= exact)
            .or_insert(exact);
    }
    for (path, recursive) in watched {
        let mode = if recursive {
            notify::RecursiveMode::Recursive
        } else {
            notify::RecursiveMode::NonRecursive
        };
        if let Err(error) = watcher.watch(&path, mode) {
            eprintln!(
                "yas-server: cannot watch font directory {}: {error}",
                path.display()
            );
        }
    }
    Some(watcher)
}

fn queue_font_event(
    events: &tokio::sync::mpsc::Sender<()>,
    roots: &[std::path::PathBuf],
    event: notify::Result<notify::Event>,
) {
    let Ok(event) = event else {
        return;
    };
    // notify's Linux backend watches IN_OPEN by default. Scanning a font
    // catalogue therefore observes its own reads unless access-only events
    // are discarded here.
    if event.kind.is_access() {
        return;
    }
    // A missing configured directory is watched through its nearest existing
    // parent. Ignore unrelated changes in that parent, but accept creation of
    // any missing ancestor and changes inside an existing font root.
    if !event.paths.is_empty()
        && !event.paths.iter().any(|path| {
            roots
                .iter()
                .any(|root| path.starts_with(root) || root.starts_with(path))
        })
    {
        return;
    }
    let _ = events.try_send(());
}

fn configured_export_policy(value: Option<&str>) -> FontExportPolicy {
    if value == Some("0") {
        FontExportPolicy::Deny
    } else {
        FontExportPolicy::Allow
    }
}

fn empty_catalog(export_policy: FontExportPolicy) -> FontCatalog {
    FontCatalog::from_paths(export_policy, std::iter::empty::<&std::path::Path>())
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use notify::event::{AccessKind, AccessMode, CreateKind};
    use notify::{Event, EventKind};

    use super::{FontExportPolicy, configured_export_policy, queue_font_event};

    #[test]
    fn font_export_defaults_on_with_an_explicit_opt_out() {
        for value in [None, Some(""), Some("1")] {
            assert_eq!(configured_export_policy(value), FontExportPolicy::Allow);
        }
        assert_eq!(configured_export_policy(Some("0")), FontExportPolicy::Deny);
    }

    #[test]
    fn font_events_ignore_reads_and_unrelated_parent_changes() {
        let roots = [PathBuf::from("/fonts"), PathBuf::from("/home/alice/.fonts")];
        let (events, mut receiver) = tokio::sync::mpsc::channel(1);

        queue_font_event(
            &events,
            &roots,
            Ok(
                Event::new(EventKind::Access(AccessKind::Open(AccessMode::Read)))
                    .add_path(PathBuf::from("/fonts/regular.ttf")),
            ),
        );
        queue_font_event(
            &events,
            &roots,
            Ok(Event::new(EventKind::Create(CreateKind::File))
                .add_path(PathBuf::from("/home/alice/unrelated"))),
        );

        assert!(receiver.try_recv().is_err());
    }

    #[test]
    fn font_events_accept_relevant_changes_and_coalesce_bursts() {
        let roots = [PathBuf::from("/fonts"), PathBuf::from("/home/alice/.fonts")];
        let (events, mut receiver) = tokio::sync::mpsc::channel(1);

        queue_font_event(
            &events,
            &roots,
            Ok(Event::new(EventKind::Create(CreateKind::File))
                .add_path(PathBuf::from("/fonts/new.ttf"))),
        );
        // Creation of a missing font root is first reported at an ancestor.
        queue_font_event(
            &events,
            &roots,
            Ok(Event::new(EventKind::Create(CreateKind::Folder))
                .add_path(PathBuf::from("/home/alice/.fonts"))),
        );

        assert_eq!(receiver.try_recv(), Ok(()));
        assert!(receiver.try_recv().is_err());
    }
}
